server:
  port: 8081
  servlet:
    context-path: /v1/user

spring:
  application:
    name: USER-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/manager_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:configserver:http://localhost:8083
  zipkin:
    base-url: http://127.0.0.1:9411/